kubevirt/kubevirt.core

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add the GitHub PR and Issue templates used by the KubeVirt org.
```release-note
None
```

Add GitHub PR and Issue templates

---

examples/play-create.yml
plugins/modules/kubevirt_vm.py
tests/unit/modules/test_module_kubevirt_vm.py

Use InstancetypeMatchers and PreferenceMatchers directly instead of providing multiple arguments to prevent unnecessary abstraction.
```release-note
None
```

kubevirt_vm: Use {Instancetype,Preference}Matchers

---

examples/play-create-min.yml
examples/play-create.yml
plugins/modules/kubevirt_vm.py
tests/unit/modules/test_module_kubevirt_vm.py

By allowing to specify the template spec unnecessary abstraction is avoided.
The following module args are replaced by the 'spec' arg:
- termination_grace_period
- interfaces
- networks
- volumes
```release-note
None
```

kubevirt_vm: Allow to specify template spec

---

examples/play-create-dv.yml
examples/play-delete-dv.yml
hack/e2e-setup.sh
plugins/modules/kubevirt_vm.py
tests/unit/modules/test_module_kubevirt_vm.py

By allowing to specify DataVolume templates VMs with persistent storage
can be created using the kubevirt_vm module.
Examples and docs will only be valid after #1 and #3 were merged.
```release-note
None
```

kubevirt_vm: Allow to specify DataVolume templates

---

plugins/modules/kubevirt_vm.py
tests/unit/modules/test_module_kubevirt_vm.py

This removes the unnecessary whitespace from the rendered VirtualMachine
template and adds a unit test for it.
Merge after #4
```release-note
None
```

kubevirt_vm: Prevent unnecessary whitespace

---

.github/workflows/ci.yml
.github/workflows/release.yml

To bypass restrictions on GitHub Actions run the docs and ci workflows manually after creating a release. GitHub Actions does not trigger other workflows from a workflow run if not using a personal access token (PAT). By calling the workflows explicitly, it is possible to work around this restriction without the need for a PAT.
```release-note
None
```

release: Run other workflows explicitly

---

.github/workflows/ci.yml

Python 3.9 is no longer supported by the latest Ansible milestone version.
```release-note
None
```

ci: Exclude py3.9 with Ansible milestone

---

changelogs/fragments/0_flatten_groups.yml
changelogs/fragments/1_add_create_groups.yml
plugins/inventory/kubevirt.py
tests/integration/targets/inventory_kubevirt/test.kubevirt.yml
tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml
tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml

This PR does two things:
- Drop creation of the namespace_vmis_group as it is redundant.
- It adds the create_groups option to the inventory, which allows to
control the creation of groups from labels on VirtualMachines. By
default it is disabled.
**Which issue(s) this PR fixes**:
Fixes #19 
```release-note
inventory: Drop creation of the namespace_vmis_group as it is redundant
inventory: Allow to control creation of additional groups
```

Flatten groups and allow to control creation of additional groups

---

changelogs/fragments/0_flatten_groups.yml
changelogs/fragments/1_add_create_groups.yml
changelogs/fragments/3_add_kubevirt_vm_info.yml

Drop old changelog fragments, they were consumed in the 1.1.0 release.
```release-note
None
```

Drop old changelog fragments

---

.ansible-lint

antsibull-changelog generates yaml format which ansible-lint doesn't like
```release-note
NONE
```

Add changelog to lint ignores

---

.ansible-lint
.github/workflows/ci.yml
.github/workflows/integration.yml
.yamllint
changelogs/changelog.yaml
changelogs/config.yaml
examples/inventory.kubevirt.yml
examples/kubesecondarydns.kubevirt.yml
examples/play-create-dv.yml
examples/play-create-min.yml
examples/play-create.yml
examples/play-delete-dv.yml
examples/play-delete.yml
examples/play-info-list.yml
examples/play-info.yml
examples/services.kubevirt.yml
galaxy.yml
plugins/inventory/kubevirt.py
requirements.yml
tests/config.yaml
tests/integration/targets/inventory_kubevirt/playbook.yml
tests/integration/targets/inventory_kubevirt/test.kubevirt.yml
tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml
tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml
tests/integration/targets/kubevirt_vm/test.kubevirt.yml

This adds yamllint to the CI linter job and sets the maximum line
length to 140 like in kubevirt/kubevirt.
Fixes #
Based on #38, merge first
```release-note
None
```

ci: Add yamllint to CI linter job

---

changelogs/changelog.yaml
galaxy.yml
plugins/inventory/kubevirt.py
requirements.yml

Bump the dependency on kubernetes.core to versions >=3.0.1 and remove the workaround introduced by 4429ac8c038afc55316b50c165429cc91b4f9f52.
Fixes #
```release-note
Depend on kubernetes.core version >=3.0.1
```

chore: Bump dependency on kubernetes.core

---

plugins/doc_fragments/k8s_auth_options.py
plugins/doc_fragments/k8s_delete_options.py
plugins/doc_fragments/k8s_state_options.py
plugins/modules/kubevirt_vm.py
plugins/modules/kubevirt_vm_info.py

Vendor the kubernetes.core doc_fragments used by this collection because it is not possible to refer to doc_fragments of dependency collections.
Fixes #
```release-note
None
```

chore: Vendor kubernetes.core doc_fragments

---

tests/integration/targets/inventory_kubevirt/cleanup.yml
tests/integration/targets/inventory_kubevirt/runme.sh

Cleanup the created the created VMs after the inventory integration tests collected the inventory test results to not leave running VMs behind after the test finished.
Fixes #
```release-note
None
```

tests: Cleanup after inventory test

---

galaxy.yml

Add .gitignore files to build_ignore since we do not need them in the released collection.
Fixes #
```release-note
None
```

galaxy.yml: Add .gitignores to build_ignore

---

plugins/inventory/kubevirt.py

Explicitly set ansible_port so it is reset in AWX inventories if the value changes from set to unset.
Fixes #
```release-note
Explicitly set ansible_port so it is reset in AWX inventories if the value changes from set to unset.
```

fix: Explicity set ansible_port

---

plugins/inventory/kubevirt.py

If no VMIs were found in a namespace then return early to avoid adding empty groups in the inventory.
Fixes #
```release-note
inventory: Empty namespaces are no longer added as groups.
```

fix: Return early to avoid adding empty groups.

---

plugins/inventory/kubevirt.py

Re-try from #69 
Docs seem to indicate compose variables should work, but they aren't actually set. Fix that by adding the composite variables to the inventory.
Fixes #
```release-note
inventory: Fix adding composite vars to the inventory.
```

fix: add composite vars to inventory

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
Makefile
galaxy.yml
test-requirements.txt
tests/requirements.txt
tests/unit/requirements.txt
tox.ini

- Add tox configuration that allows to build a venv for development and to
format source files. To make use of it add appropriate Makefile targets.
- Drop unneeded requirements from requirements.txt and
test-requirements.txt and add needed requirements.
- Add tox-ansible configuration that allows to run tests with all
required ansible and python versions. Add Makefile targets to make use
of it.
- Add vscode configuration that allows to develop, test and debug the
collection.
Fixes #
```release-note
None
```

Add helper to build virtualenv and vscode configuration

---

plugins/inventory/kubevirt.py
test-requirements.txt
tests/unit/plugins/inventory/test_kubevirt.py
tests/unit/utils/ansible_module_mock.py
tests/unit/utils/merge_dicts.py

This changes the inventory plugin so that it sets the ansible_connection to winrm if it detected a Windows host. If it did not detect a Windows host the ansible_connection is no longer set, so Ansible falls back to its default value of ssh.
Fixes #33
```release-note
Set ansible_connection to winrm for Windows hosts
```

feat: Set ansible_connection to winrm for Windows hosts

---

plugins/modules/kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm.py

To properly wait for a state change the wait_condition needs to
adapted to the state of running.
Fixes #
Wait for #88 to go in first
```release-note
Adapt the wait_condition to properly wait for state changes.
```

fix(kubevirt_vm): Set wait_condition based on running

---

plugins/modules/kubevirt_vm_info.py
tests/unit/plugins/modules/test_kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm_info.py

Add the running parameter to kubevirt_vm_info from which the wait_condition is derived from when parameter wait is set to yes.
Fixes #
```release-note
Add the running parameter to kubevirt_vm_info that controls which ready condition to wait for.
```

feat(kubevirt_vm_info): Set wait_condition based on running

---

tests/unit/plugins/modules/test_kubevirt_vm.py

- It adds unit tests for the render_template function. These test cases cover all cases for non-mandatory fields in the VM template.
Fixes # [CNV-35424](https://issues.redhat.com/browse/CNV-35424)
```release-note
None
```

tests: add render_template unit tests

---

plugins/inventory/kubevirt.py
tests/unit/plugins/inventory/test_kubevirt.py

Increases unit test kubevirt inventory plugin coverage. Also, it fixes some minor issues found:
- Loop ranging over vmi labels.
- Minor typo on comment.
Unit test coverage has improved from 50% to 83%.
Fixes# [CNV-41341](https://issues.redhat.com/browse/CNV-41341)
```release-note
None
```

Add inventory unit tests

---

docs/docsite/links.yml
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py
plugins/modules/kubevirt_vm_info.py

Provide links for docsite and improve docs by adding markup.
Fixes #
```release-note
None
```

Provide links for docsite and improve docs by adding markup

---

README.md
galaxy.yml
plugins/inventory/kubevirt.py
requirements.yml

Ensure compatibility with kubernetes.core >=3.10,<4.1.0 by replacing deprecated imports of HAS_K8S_MODULE_HELPER and k8s_import_exception.
Fixes #30
Fixes #31 
Fixes #99
```release-note
Ensure compatibility with kubernetes.core >=3.10,<4.1.0
```

fix: Ensure compatibility with kubernetes.core >=3.10,<4.1.0

---

tests/integration/targets/kubevirt_vm/runme.sh
tests/integration/targets/kubevirt_vm/verify.yml
tests/integration/targets/kubevirt_vm/wait_for_vm.yml

- This changes the runme.sh of the kubevirt_vm integration tests to retry
the connection to the VM until a login is possible. This is necessary
since it is not possible with Ansible alone to retry a task in case the
connection failed with the unreachable status. This can happen when the
sshd of the VM already accepts connections but a login is not yet
possible because the VM is still booting up.
- Assert there are no or expected changes in verify.yml of the kubevirt_vm
integration test. This is necessary since in downstream tests the
kubemacpool operator might add annotations to the VM which can trigger a
changed result.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

Make kubevirt_vm tests more robust

---

.github/workflows/ci.yml
.github/workflows/integration.yml

Python 3.10 is no longer supported by ansible-core devel, so this excludes it from the test matrices.
Fixes #
```release-note
None
```

fix(ci): Do not test ansible-core devel with py3.10

---

tests/unit/plugins/inventory/test_kubevirt.py
tests/unit/plugins/inventory/test_kubevirt_composable_vars.py

It refactors several fixtures to allow the use of any inventory mock. The affected fixtures are:
- host_vars
- add_group
- add_child
- add_host
It also adds unit tests for the following inventory functions:
- set_composable_vars
- format_dynamic_api_exc
Finally, it increases test coverage for `get_vmis_for_namespace` function.
Fixes # [CNV-41852](https://issues.redhat.com/browse/CNV-41852)
Follow-up of PR #96 
```release-note
NONE
```

Inventory unit tests

---

.github/workflows/ci.yml
.github/workflows/integration.yml

Python 3.10 is no longer supported by ansible-core milestone, so this excludes it from the test matrices.
Fixes #
```release-note
None
```

fix(ci): Do not test ansible-core milestone with py3.10

---

README.md
plugins/modules/kubevirt_vm.py
requirements.txt
tests/unit/plugins/modules/test_kubevirt_vm.py
tests/unit/requirements.txt

Drop the dependency on Jinja2 in the kubevirt_vm module by using dicts to construct a VM instead of rendering jinja templates internally.
Fixes #
```release-note
Dropped the dependency on Jinja2
```

cleanup(kubevirt_vm): Drop dependency on Jinja2

---

.yamllint
examples/inventory.kubevirt.yml
examples/kubesecondarydns.kubevirt.yml
examples/services.kubevirt.yml
plugins/doc_fragments/kubevirt_auth_options.py
plugins/inventory/kubevirt.py
tests/integration/targets/inventory_kubevirt/test.kubevirt.yml
tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml
tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml
tests/integration/targets/kubevirt_vm/test.kubevirt.yml
tests/unit/plugins/inventory/test_kubevirt.py
tests/unit/plugins/inventory/test_kubevirt_connections_compatibility.py
tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
tests/unit/plugins/inventory/test_kubevirt_parse.py

The support for connections to multiple clusters in the inventory
plugin is dropped to better align with user expectations and how other
inventories work. If inventories of multiple clusters are needed the
inventory can be run multiple times with different configurations.
This also helps to clean up the code and make it simpler.
Fixes #
Based on #114, rebase and merge after it is merged.
```release-note
inventory: [Breaking change] Support for multiple connections was dropped
```

cleanup(inventory): Drop support for multiple connections

---

.gitignore
examples/cache.kubevirt.yml
plugins/inventory/kubevirt.py
test-requirements.txt
tests/integration/targets/inventory_kubevirt/runme.sh
tests/integration/targets/inventory_kubevirt/test.cache.kubevirt.yml
tests/integration/targets/inventory_kubevirt/verify.yml
tests/unit/plugins/inventory/blackbox/test_kubevirt_ansible_connection_winrm.py
tests/unit/plugins/inventory/blackbox/test_kubevirt_set_composable_vars.py
tests/unit/plugins/inventory/blackbox/test_kubevirt_stopped_vm.py
tests/unit/plugins/inventory/conftest.py
tests/unit/plugins/inventory/test_kubevirt.py
tests/unit/plugins/inventory/test_kubevirt_add_host.py
tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
tests/unit/plugins/inventory/test_kubevirt_parse.py
tests/unit/plugins/inventory/test_kubevirt_populate_inventory_from_namespace.py
tests/unit/plugins/inventory/test_kubevirt_set_ansible_host_and_port.py
tests/unit/plugins/inventory/test_kubevirt_set_common_vars.py
tests/unit/plugins/inventory/test_kubevirt_set_vars_from_vmi.py
tests/unit/requirements.txt

Fix inventory source caching by separating the fetching of objects and
populating the inventory. This way objects can be fetched from the K8S
API or from a configured cached and the cache related parameters on the
plugin now actually work.
To make this possible use dicts instead of ResourceFields where possible 
to allow easier serialization/deserialization of objects fetched from
the K8S API.
Fixes #
Merge after #117 
```release-note
Caching of inventory sources was fixed and is now working.
```

fix(inventory): Fix inventory source caching

---

examples/play-create-run-strategy.yml
plugins/modules/kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm.py

This change adds support for setting the RunStrategy of a VM.
Depending on the value set the wait condition for the VM is adjusted. For the values Always, RerunOnFailure or Once the wait condition will wait for the VM to run and be ready. For the value Halted the wait condition will wait for the VM to not exist. For the value Manual the wait condition is not set.
Fixes #
```release-note
Added support for setting the RunStrategy of a VM
```

feat(kubevirt_vm): Add support for RunStrategy

---

hack/e2e-setup.sh

Use the bundled common-instancetypes deployed by virt-operator instead of deploying common-instancetypes manually.
Fixes #
```release-note
None
```

e2e-setup: Use virt-operator to deploy common-instancetypes

---

.github/workflows/ci.yml
.gitignore
plugins/module_utils/info.py
plugins/modules/kubevirt_vm_info.py
plugins/modules/kubevirt_vmi_info.py
tests/integration/targets/kubevirt_vmi_info/generate.yml
tests/integration/targets/kubevirt_vmi_info/playbook.yml.j2
tests/integration/targets/kubevirt_vmi_info/runme.sh
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt
tests/unit/plugins/modules/test_kubevirt_vm_info.py
tests/unit/plugins/modules/test_kubevirt_vmi_info.py

Add the kubevirt_vmi_info module which allows to fetch information about
VirtualMachineInstance(s).
Fixes #
```release-note
Added the kubevirt_vmi_info module which allows to fetch information about
VirtualMachineInstance(s).
```

feat: Add kubevirt_vmi_info module

---

.github/workflows/ci.yml
.github/workflows/integration.yml
README.md
tests/config.yml

Bump the tested Ansible and Python version to include Ansible 2.18 and Python 3.13.
Fixes #
```release-note
The collection is now tested with Ansible 2.18 and Python 3.13.
```

chore: Bump tested Ansible and Python versions

---

.github/workflows/integration.yml

Drop the flag for common-instancetypes deployment that was removed previously.
Fixes #
```release-note
None
```

ci(integration): Drop common-instancetypes deployment

---

.github/workflows/ci.yml
.gitignore

ansible-compat 25.0.0 now stores its cache in .ansible. Ignore this location when running ansible-lint and in .gitignore.
Fixes #
```release-note
None
```

fix(ci): Exclude ansible-compat's new cache location

---

plugins/inventory/kubevirt.py
tests/unit/plugins/inventory/test_kubevirt_inventory_options.py
tests/unit/plugins/inventory/test_kubevirt_set_ansible_host_and_port.py

This adds the unset_ansible_port option to the inventory, which allows to control if the value of ansible_port should be unset if no non-default value was found.
Fixes #172 
```release-note
The unset_ansible_port option was added to the inventory. It allows to control if the value of ansible_port should be unset if no non-default value was found.
```

feat(inventory): Add unset_ansible_port option

---

plugins/inventory/kubevirt.py
tests/unit/plugins/inventory/test_kubevirt_parse.py
tests/unit/plugins/modules/test_kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm_info.py
tests/unit/plugins/modules/test_kubevirt_vmi_info.py
tests/unit/utils/ansible_module_mock.py

ansible-core 2.19 changes the way templates are trusted and provides a new way of patching module args in unit tests.
With this commit the following changes are made to ensure compatibility with ansible-core >= 2.19:
- Mark inputs to composable as trusted to align with the new template trust model.
- Utilize the updated method for patching module arguments in unit tests if available.
- Replace direct access to the self._cache attribute with the inventory's cache property.
Fixes #
```release-note
The collection now supports ansible-core >= …
```

fix: Ensure compatibility with ansible-core >= 2.19

---

plugins/inventory/kubevirt.py
tests/unit/plugins/inventory/conftest.py
tests/unit/plugins/inventory/test_kubevirt_get_resources.py

If no namespaces were specified in the inventory config try to get all available namespaces by trying to list OCP projects first. If the resource was not found (no OCP cluster) fall back to regular namespaces.
Fixes #166 
```release-note
If no namespaces were configured the inventory now tries to use OCP Projects if available.
```

feat(inventory): Use OCP projects if available

---

README.md
galaxy.yml
plugins/module_utils/diff.py
plugins/module_utils/info.py
plugins/modules/kubevirt_vm.py
plugins/modules/kubevirt_vm_info.py
plugins/modules/kubevirt_vmi_info.py
requirements.yml
tests/unit/plugins/modules/test_kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm_info.py
tests/unit/plugins/modules/test_kubevirt_vmi_info.py

In order to make use of new features in kubernetes.core bump its minimum
version to 5.2.0.
Add the hidden_fields argument to kubevirt_vm and kubevirt_{vm,vmi}_info
which allows to hide and ignore certain fields in the returned definition
of a VM or VMI. By default this argument is set to ignore changes to the
kubemacpool.io/transaction-timestamp annotation, which may change at any
time and cause the modules to return a changed status although nothing
has changed other than this annotation.
Fix the change detection of kubernetes.core temporarily by monkey
patching the service.diff_objects function. This fix should be removed
once it was merged into kubernetes.core. A dummy _patch_diff_objects
function is introduced to satisfy ansible linters.
**Which …

feat(modules): Add hidden_fields argument

---

plugins/modules/kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm.py

Allow switching between running and run_strategy by always clearing the other value. E.g. if run_strategy was provided then running set to None to clear it or vice versa.
Fixes #152 
```release-note
fix(kubevirt_vm): It is now possible to switch between running and run_strategy
```

fix(kubevirt_vm): Allow switching between running and run_strategy

---

hack/e2e-setup.sh

Wait for CDI to be available after deploying it.
Also add the missing --deploy-kubevirt-cdi flag to the usage help.
Fixes #
```release-note
None
```

fix(e2e-setup.sh): Wait for CDI to be available

---

README.md
changelogs/changelog.yaml
galaxy.yml
requirements.yml

This bumps the dependency on kubernetes.core to >=5.2.0,<7.0.0 and the version and changelog of the collection to 2.2.3.
Fixes #191 
```release-note
Bumps the dependency on kubernetes.core to >=5.2.0,<7.0.0
```

Bump dependency on kubernetes.core and collection version

---

.github/workflows/ci.yml
.github/workflows/integration.yml

This Python version is no longer supported by devel versions of ansible-core.
Fixes #
```release-note
None
```

chore(ci): Exclude Python 3.11 from devel

---

.github/workflows/ci.yml
.github/workflows/integration.yml

This Python version is no longer supported by milestone versions of ansible-core.
Fixes #
```release-note
None
```

chore(ci): Exclude Python 3.11 from milestone
