kubevirt/kubevirt.core

.github/workflows/ci.yml
.github/workflows/docs.yml
LICENSE
README.md
hack/e2e-setup.sh
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py
test-requirements.txt
tests/.kubeconfig
tests/integration/inventory
tests/unit/conftest.py
tests/unit/modules/test_module_kubevirt_vm.py
tests/unit/requirements.txt
tests/unit/utils/ansible_module_mock.py

This PR contains several commits fixing issues found during linting.
```release-note
None
```

Fix issues found during linting

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
README.md
docs/index.rst
examples/inventory.kubevirt.yml
examples/kubesecondarydns.kubevirt.yml
examples/play-create-dv.yml
examples/play-create-min.yml
examples/play-create.yml
examples/play-delete-dv.yml
examples/play-delete.yml
examples/services.kubevirt.yml
galaxy.yml
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py
tests/integration/targets/inventory_kubevirt/runme.sh
tests/unit/modules/test_module_kubevirt_vm.py

This replaces all occurences of the old kubernetes.core name.
```release-note
Renamed collection to kubevirt.core
```

Rename collection to kubevirt.core

---

.ansible-lint
.github/workflows/ci.yml
galaxy.yml

CI: update integration.yml to final location
CI: silence the yaml-truthy linter rule
Bump version to 0.1.1
CI: update integration.yml to final location
CI: silence the yaml-truthy linter rule
n/a
```release-note
NONE
```

Bump to 0.1.1

---

changelogs/changelog.yaml
meta/runtime.yml

Fix typo in meta/runtime
```release-note
NONE
```

Meta runtime fix

---

changelogs/changelog.yaml
galaxy.yml

Bump version to 1.0.0 for the initial release.
```release-note
Release version 1.0.0 as the initial release.
```

Bump version to 1.0.0

---

README.md

README.md: Drop note about supported collection for now
```release-note
None
```

README.md: Drop note about supported collection for now

---

.github/workflows/ci.yml
.github/workflows/integration.yml

Workaround an issue in a github action
Fixes #17 
```release-note
NONE
```

install galaxy ansible.posix, not from sources

---

galaxy.yml

Bump version to 1.1.0
```release-note
None
```

Bump version to 1.1.0

---

changelogs/changelog.yaml

changelog.yaml: Fix indentation for linter
```release-note
None
```

changelog.yaml: Fix indentation for linter

---

.ansible-lint
.github/workflows/ci.yml
.github/workflows/integration.yml
README.md
meta/runtime.yml
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py

ansible-core 2.13 went EOL November 6th
Also fixed linter was reporting errors
Fixes #
```release-note
NONE
```

Set minimum ansible-core>=14

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/extra-docs-linting.yml
.github/workflows/integration.yml
.github/workflows/release.yml
README.md

Use Python 3.9 - 3.12 and Ansible 2.14 - 2.16, devel and milestone to run
tests of the collection. Use the latest stable python version in test setups
where sensible. Instead of using the integration.yml workflog from main
use it from the same commit as the test runs instead.
See [here](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) for a matrix of supported Python and Ansible versions.
Fixes #
```release-note
None
```

.github: Update tested Ansible and Python versions

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/extra-docs-linting.yml
.github/workflows/integration.yml
.github/workflows/release.yml

Cleanup the .github actions:
- Use the same syntax and/or commands where possible
- Drop unnecessary parameters and steps / commands
- In the all-green job ensure that all CI jobs passed
- Update the naming of jobs
- Review permissions and grant write permission only where
necessary (repo is set to read-only by default)
- Review installed dependencies (try to fix the failing docs job)
- Run yamllint and fix findings
- Replace deprecated set-output syntax
Fixes #
```release-note
None
```

.github: Cleanup actions

---

README.md
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py
plugins/modules/kubevirt_vm_info.py

Update README.md to include all modules of the collection and keep module descriptions in sync.
Fixes #
```release-note
None
```

chore: Update README.md

---

README.md
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py
plugins/modules/kubevirt_vm_info.py
requirements.txt
tests/config.yaml
tests/unit/requirements.txt

Update the requirements throughout the project to be in sync and to reflect the current state of dependencies.
Fixes #
```release-note
None
```

cleanup: Update requirements throughout the project

---

.github/workflows/ci.yml

Install and run shellcheck in the CI linter job. Lint all files matching '*.sh' in the tree.
Fixes #
```release-note
None
```

ci: Run shellcheck in CI linter job

---

galaxy.yml

Bump collection version to 1.2.0, this should create a release.
Fixes #
```release-note
None
```

chore: Bump collection version to 1.2.0

---

.github/workflows/integration.yml
.github/workflows/release.yml
tests/integration/targets/inventory_kubevirt/runme.sh
tests/integration/targets/kubevirt_vm/runme.sh
tests/integration/targets/kubevirt_vm/verify.yml
tests/integration/targets/kubevirt_vm_info/runme.sh

Cleanup GitHub Action oddities by:
- Fix release workflow failing because of non-zero exit
- Use default shell when deploying KubeVirt
- Fix non failing integration tests
- Fix failing integration tests
Fixes #
```release-note
None
```

Cleanup GitHub Action oddities

---

.github/workflows/ci.yml

Drop the all green job which essentially duplicates functionality provided by GitHub Actions already.
Fixes #
```release-note
None
```

ci: Drop all green job

---

changelogs/changelog.yaml
galaxy.yml

Bump version to 1.2.1 and include a change summary.
Fixes #
```release-note
None
```

chore: Bump version to 1.2.1

---

.yamllint

Ignore errors found by yamllint in generated files.
Fixes #
```release-note
None
```

fix: Ignore generated files in yamllint

---

galaxy.yml

Remove CONTRIBUTING.md from build_ignore and add docs/requirements.txt to build_ignore.
Fixes #
```release-note
None
```

galaxy.yaml: Update build_ignore again

---

README.md
plugins/inventory/kubevirt.py
plugins/modules/kubevirt_vm.py

This PR contains some small doc changes.
Fixes #
```release-note
None
```

Doc updates

---

changelogs/changelog.yaml
galaxy.yml

Bump version to 1.2.2 and add release summary.
Fixes #
```release-note
Bumped version to 1.2.2
```

chore: Bump version to 1.2.2

---

tests/integration/targets/inventory_kubevirt/cleanup.yml

We are deleting VMs, not creating VMs. Therefore change the names to reflect that.
Fixes #
```release-note
None
```

chore: Fix names in inventory cleanup

---

changelogs/changelog.yaml
galaxy.yml

No functional changes, hotfix release to retrigger the downstream build and to keep in sync with Ansible Automation Hub.
Fixes #
```release-note
None
```

chore: Bump version to 1.2.3

---

CHANGELOG.rst

Update CHANGELOG.rst to conform to semantic versioning of the collection.
Fixes #
```release-note
None
```

chore: Update CHANGELOG.rst

---

hack/e2e-setup.sh

With this change hack/e2e-setup.sh configures a local registry when the --create-registry argument is passed to it. This registry can be used to test local images. The registry is optional and not created by default.
Fixes #
```release-note
None
```

tests: Add --create-registry to hack/e2e-setup.sh

---

tests/requirements.txt
tests/unit/requirements.txt

Add the requirements.txt with requirements needed by ansible-test units.
Without it `ansible-test units --docker` does not work anymore.
Fixes #
```release-note
None
```

chore: Add requirements.txt for ansible-test units

---

galaxy.yml

Bump version to 1.3.0
Fixes #
```release-note
None
```

chore: Bump version to 1.3.0

---

docs/developing.md
docs/testing.md
galaxy.yml
test-requirements.txt

Update the testing instructions and file exclusions in galaxy.yml, so they still make sense in a released version of this collection.
Fixes #
```release-note
None
```

chore: Update testing instructions

---

galaxy.yml

Bump version to 1.3.1
Fixes #
```release-note
None
```

chore: Bump version to 1.3.1

---

changelogs/changelog.yaml
galaxy.yml

Bump version once more and include appropriate changelogs this time.
Fixes #
```release-note
None
```

chore: Bump version to 1.3.2

---

plugins/modules/kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm.py

Cleanup the YAML passed to the k8s module so it conforms to yaml output you would expect from yaml.dump. Also refactor the tests to get rid of duplicate definitions and make use of yaml.dump.
Fixes #
```release-note
None
```

cleanup: Cleanup YAML passed to k8s module

---

changelogs/changelog.yaml
galaxy.yml

Bump version and add changelog with release summary.
Fixes #
```release-note
Bumped version to 1.4.0
```

chore: Bump version to 1.4.0

---

.github/workflows/ci.yml
.github/workflows/integration.yml

Bump the tested ansible-core versions in ci.yml and integration.yml to the latest
supported versions (2.15-2.17).
Fixes #
```release-note
None
```

Bump tested ansible-core versions to 2.15-2.17

---

README.md
docs/requirements.txt
meta/runtime.yml

Update the supported versions of ansible-core to >=2.15.
Fixes #
```release-note
Updated the supported versions of ansible-core to >=2.15.
```

chore: Update supported ansible-core versions to >=2.15

---

tests/integration/targets/kubevirt_vm/verify.yml

Fix the assertion that was introduced in
2521e8ba245c7ceae8ace45da63366b6d8a4b7b5 by removing the superfluous 'd' at the end of the variable names.
Fixes #
```release-note
None
```

fix(tests,kubevirt_vm): Fix assertion in verify.yml

---

tests/integration/targets/kubevirt_vm/runme.sh

Fixes #
```release-note
NONE
```

kubevirt_vm integration tests: changed ssh key type to RSA for FIPS mode

---

tests/unit/plugins/inventory/test_kubevirt.py

It fixes concerns posted on https://github.com/kubevirt/kubevirt.core/pull/96
Fixes # [CNV-41852](https://issues.redhat.com/browse/CNV-41852)
```release-note
NONE
```

tests: Address comments of #96

---

requirements.yml

Ensure compatibility with kubernetes.core >=3.1.0,<6.0.0 and update requirements.yml.
Fixes #110
```release-note
Ensure compatibility with kubernetes.core >=3.10,<6.0.0 and update requirements.yml.
```

chore: Ensure compatibility with kubernetes.core >=3.1.0,<6.0.0

---

.github/workflows/ci.yml
.github/workflows/integration.yml
.gitignore
.vscode/launch.json
.vscode/module_args/kubevirt_vm.json
.vscode/module_args/kubevirt_vm_info.json
Makefile
galaxy.yml
tests/unit/plugins/modules/test_kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm_info.py

This contains several minor improvements and cleanups, see the commit messages.
Fixes #
```release-note
None
```

Several minor improvements

---

docs/testing.md

It documents how the coverage analyzer can be used to create a test coverage report.
Fixes #
```release-note
None
```

Add documentation running coverage analysis.

---

OWNERS

/cc @0xFelix 
/cc @jcanocan 
Fixes #
```release-note
NONE
```

chore(OWNERS): make jcanocan an approver

---

README.md
plugins/inventory/kubevirt.py
tests/unit/plugins/inventory/blackbox/test_kubevirt_ansible_connection_winrm.py
tests/unit/plugins/inventory/blackbox/test_kubevirt_set_composable_vars.py
tests/unit/plugins/inventory/blackbox/test_kubevirt_stopped_vm.py
tests/unit/plugins/inventory/test_kubevirt.py
tests/unit/plugins/inventory/test_kubevirt_add_host.py
tests/unit/plugins/inventory/test_kubevirt_connections_compatibility.py
tests/unit/plugins/inventory/test_kubevirt_fetch_objects.py
tests/unit/plugins/inventory/test_kubevirt_format_dynamic_api_exc.py
tests/unit/plugins/inventory/test_kubevirt_get_resources.py
tests/unit/plugins/inventory/test_kubevirt_get_ssh_services_for_namespace.py
tests/unit/plugins/inventory/test_kubevirt_parse.py
tests/unit/plugins/inventory/test_kubevirt_populate_inventory_from_namespace.py
tests/unit/plugins/inventory/test_kubevirt_set_ansible_host_and_port.py
tests/unit/plugins/inventory/test_kubevirt_set_common_vars.py
tests/unit/plugins/inventory/test_kubevirt_set_vars_from_vmi.py
tests/unit/plugins/modules/test_kubevirt_vm.py
tests/unit/plugins/modules/test_kubevirt_vm_info.py

This PR contains several small cleanups:
- Mark all methods of the inventory which should be private with a underscore
prefix in their name.
- Add missing docstring for the _connections_compatibility method.
- Simplify kubevirt_vmtests by not using fixtures if not needed.
- Simplify kubevirt_vm_info tests by not using fixtures if not needed.
- Update supported kubernetes.core versions in README.md
Fixes #
Merge after #119 
```release-note
None
```

Several small cleanups

---

changelogs/changelog.yaml
galaxy.yml

Bump version and add changelog with release summary.
Fixes #
```release-note
None
```

chore: Bump version to 2.0.0

---

.yamllint

Fix ansible-lint warnings by adding required yamllint options.
Fixes #
```release-note
None
```

cleanup(yamllint): Add yamllint options required by ansible-lint

---

.gitignore
tests/integration/targets/inventory_kubevirt/cleanup.yml.j2
tests/integration/targets/inventory_kubevirt/generate.yml
tests/integration/targets/inventory_kubevirt/playbook.yml.j2
tests/integration/targets/inventory_kubevirt/runme.sh
tests/integration/targets/inventory_kubevirt/test.cache.kubevirt.yml.j2
tests/integration/targets/inventory_kubevirt/test.kubevirt.yml.j2
tests/integration/targets/inventory_kubevirt/test.label.kubevirt.yml.j2
tests/integration/targets/inventory_kubevirt/test.net.kubevirt.yml.j2
tests/integration/targets/inventory_kubevirt/verify.yml.j2
tests/integration/targets/kubevirt_vm/generate.yml
tests/integration/targets/kubevirt_vm/playbook.yml.j2
tests/integration/targets/kubevirt_vm/runme.sh
tests/integration/targets/kubevirt_vm/test.kubevirt.yml.j2
tests/integration/targets/kubevirt_vm/verify.yml.j2
tests/integration/targets/kubevirt_vm/wait_for_vm.yml.j2
tests/integration/targets/kubevirt_vm_info/generate.yml
tests/integration/targets/kubevirt_vm_info/playbook.yml.j2
tests/integration/targets/kubevirt_vm_info/runme.sh

Run the integration tests for inventory_kubevirt, kubevirt_vm and kubevirt_vm_info
in a random namespace and cleanup after the tests finish.
Fixes #126 
```release-note
None
```

Run integration tests in random namespaces

---

tests/integration/targets/inventory_kubevirt/runme.sh
tests/integration/targets/kubevirt_vm/runme.sh
tests/integration/targets/kubevirt_vm_info/runme.sh
tests/integration/targets/kubevirt_vmi_info/runme.sh

Allows to export additional environment variables to the inetgration targets
Fixes #
```release-note
None
```

Source extra_env.sh file if exists in integration tests

---

renovate.json

Add renovate configuration to automatically update used software versions in e2e-setup and the github actions used by this repository.
Fixes #
```release-note
None
```

chore(renovate): Add renovate config

---

renovate.json

Format the renovate config and enable the dashboard for easier overview.
Fixes #
```release-note
None
```

renovate: Enable dashboard and format config

---

changelogs/changelog.yaml
galaxy.yml

Bump version and add changelog with release summary.
Fixes #
```release-note
None
```

chore: Bump version to 2.1.0

---

tests/sanity/ignore-2.19.txt

Add sanity ignore file for ansible 2.19 to make CI pass again.
Fixes #
```release-note
None
```

chore: Add sanity ignore for ansible 2.19

---

OWNERS

Drop inactive reviewer @opokornyy from OWNERS.
Thanks Ondrej for your contributions!
Fixes #
```release-note
None
```

OWNERS: Drop opokornyy

---

hack/e2e-setup.sh

Bump to KubeVirt 1.4.0 and drop manual deployment of common-instancetypes as they are now deployed by KubeVirt by default.
Fixes #
```release-note
None
```

chore(e2e-setup): Bump to KubeVirt 1.4.0

---

.github/workflows/ci.yml
.github/workflows/integration.yml
README.md

Bump to python >=3.10,<=3.13 and ansible-core >=2.16,<=2.19.
Fixes #
```release-note
The collection tests and supports python >=3.10,<=3.13 and ansible-core >=2.16,<=2.19.
```

chore: Bump supported python and ansible-core versions

---

changelogs/changelog.yaml
galaxy.yml

Bump version to 2.2.0 and add a changelog entry for it.
Fixes #
```release-note
This release brings some new features and enables compatibility with ansible-core-2.19.
```

chore: Bump version to 2.2.0

---

changelogs/changelog.yaml
galaxy.yml

Bump version and update changelog for release 2.2.1
Fixes #
```release-note
None
```

Bump version and update changelog for release 2.2.1

---

README.md

Add kubevirt_vmi_info to README.md
Fixes #
```release-note
None
```

docs: Add kubevirt_vmi_info to README.md

---

changelogs/changelog.yaml
galaxy.yml
meta/runtime.yml

Bump minimum Ansible version to 2.16
Bump version and update changelog for release 2.2.2
This is a maintenance release to trigger a rebuild. No functional changes.
Fixes #
```release-note
None
```

Bump minimum ansible and collection versions

---

README.md

Use an absolute link for the LICENSE so it can be accessed when looking at the README.md on Ansible Galaxy.
Fixes #
```release-note
None
```

docs(README.md): Use absolute link for LICENSE

---

test-requirements.txt

Add missing dependency on typing-extensions to test-requirements.txt.
Fixes #
```release-note
None
```

chore(deps): Add missing test dependency

---

tests/sanity/ignore-2.20.txt

Add ignore file for ansible-core 2.20
Fixes #
```release-note
None
```

chore: Add ignore file for ansible-core 2.20
